#!/usr/bin/env bats

# Tests for scripts/deploy/interactive_wizard.sh

setup() {
    # shellcheck disable=SC2154
    cd "$BATS_TEST_DIRNAME/../.." || exit 1
}

##region Argument Parsing Tests

@test "wizard requires --env argument" {
    run scripts/deploy/interactive_wizard.sh
    [ "$status" -ne 0 ]
    [[ "$output" == *"--env is required"* ]]
}

@test "wizard script is executable" {
    [ -x scripts/deploy/interactive_wizard.sh ]
}

@test "wizard script has valid bash syntax" {
    run bash -n scripts/deploy/interactive_wizard.sh
    [ "$status" -eq 0 ]
}

@test "wizard fails with clear error when stdin is not a TTY" {
    # Simulate non-TTY stdin (as in Docker without -it) by redirecting from /dev/null
    run bash -c "scripts/deploy/interactive_wizard.sh --env=test-qa3 </dev/null 2>&1"
    [ "$status" -ne 0 ]
    [[ "$output" == *"Interactive mode requires a TTY"* ]]
    [[ "$output" == *"docker run -it"* ]]
}

@test "wizard non-TTY error message includes --defaults hint" {
    run bash -c "scripts/deploy/interactive_wizard.sh --env=test-qa3 </dev/null 2>&1"
    [ "$status" -ne 0 ]
    [[ "$output" == *"--defaults"* ]]
}

@test "wizard non-TTY error does not say Phase 1 cancelled" {
    run bash -c "scripts/deploy/interactive_wizard.sh --env=test-qa3 </dev/null 2>&1"
    [ "$status" -ne 0 ]
    [[ "$output" != *"Phase 1 cancelled"* ]]
}

##endregion

##region Config Generation Tests

@test "wizard generates valid YAML structure via real generate_config_yaml" {
    # Exercise the real generate_config_yaml from interactive_wizard.sh by
    # sourcing the wizard and calling the function directly with known variables.
    local test_dir
    test_dir=$(mktemp -d)
    cd "$test_dir"
    mkdir -p conf

    # Source the wizard (which also sources lib.sh)
    # shellcheck disable=SC1090
    source "$BATS_TEST_DIRNAME/../../scripts/deploy/interactive_wizard.sh" 2>/dev/null || true

    # Set up test variables
    DT_TENANT="test.live.dynatrace.com"
    DT_TOKEN="token123"
    SF_ACCOUNT="org-account"
    DEPLOYMENT_ENV="test-env"
    TAG="test-tag"
    LOG_LEVEL="WARN"
    PROCEDURE_TIMEOUT="3600"
    DEPLOY_DISABLED_PLUGINS=1
    WIZARD_ENV="testenv"
    PLUGINS_MODE="all"
    SELECTED_PLUGINS=()
    declare -A PLUGIN_OVERRIDES
    RESOURCE_MONITOR_QUOTA=""
    OTEL_LOGS_DISABLED=""
    OTEL_SPANS_DISABLED=""
    OTEL_METRICS_DISABLED=""
    OTEL_EVENTS_DISABLED=""
    OTEL_BIZ_EVENTS_DISABLED=""
    OTEL_MAX_CONSECUTIVE_API_FAILS=""

    # Test config generation using the real function
    local config_file="$test_dir/test-config.yml"
    generate_config_yaml "$config_file"

    # Verify file was created
    [ -f "$config_file" ]

    # Verify it contains expected keys
    grep -q "dynatrace_tenant_address" "$config_file"
    grep -q "snowflake" "$config_file"
    grep -q "deployment_environment" "$config_file"
    grep -q "test.live.dynatrace.com" "$config_file"

    # Verify token is NOT written as a real value (only placeholder comment)
    run grep -q "token123" "$config_file"
    [ "$status" -ne 0 ]
    grep -q "DTAGENT_TOKEN" "$config_file"

    # Verify no duplicate core.snowflake: keys
    local snowflake_count
    snowflake_count=$(grep -c "^  snowflake:" "$config_file" || true)
    [ "$snowflake_count" -le 1 ]

    cd - > /dev/null
    rm -rf "$test_dir"
}

@test "wizard generates valid YAML structure (legacy test)" {
    # Create a temporary directory for test
    local test_dir
    test_dir=$(mktemp -d)
    cd "$test_dir"
    mkdir -p conf

    # Create a simple test that just checks the config generation function
    # by sourcing the lib and defining the function directly
    source "$BATS_TEST_DIRNAME/../../scripts/deploy/lib.sh"

    # Set up test variables
    DT_TENANT="test.live.dynatrace.com"
    DT_TOKEN="token123"
    SF_ACCOUNT="org-account"
    DEPLOYMENT_ENV="test-env"
    TAG="test-tag"
    LOG_LEVEL="WARN"
    PROCEDURE_TIMEOUT="3600"
    DEPLOY_DISABLED_PLUGINS=1

    # Define the generate_config_yaml function (from wizard)
    generate_config_yaml() {
        local output_file="$1"

        # Create YAML structure
        cat > "$output_file" << EOFYAML
# DSOA Configuration - Generated by interactive wizard
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

core:
  dynatrace_tenant_address: "$DT_TENANT"
  snowflake:
    account_name: "$SF_ACCOUNT"
  deployment_environment: "$DEPLOYMENT_ENV"
  log_level: "$LOG_LEVEL"
  procedure_timeout: $PROCEDURE_TIMEOUT
EOFYAML

        if [[ -n "$TAG" ]]; then
            echo "  tag: \"$TAG\"" >> "$output_file"
        fi
    }

    # Test config generation
    local config_file="$test_dir/test-config.yml"
    generate_config_yaml "$config_file"

    # Verify file was created
    [ -f "$config_file" ]

    # Verify it contains expected keys
    grep -q "dynatrace_tenant_address" "$config_file"
    grep -q "snowflake" "$config_file"
    grep -q "deployment_environment" "$config_file"
    grep -q "test.live.dynatrace.com" "$config_file"

    cd - > /dev/null
    rm -rf "$test_dir"
}

##endregion

##endregion

##region derive_env_defaults Tests

# Helper: run derive_env_defaults logic in a clean subshell.
# Args: env_val [pre_dep] [pre_tag]
_run_derive() {
    local env_val="$1"
    local pre_dep="${2:-}"
    local pre_tag="${3:-}"

    bash -c "
        WIZARD_ENV='$env_val'
        DEPLOYMENT_ENV='$pre_dep'
        TAG='$pre_tag'

        derive_env_defaults() {
            if [[ -z \"\$DEPLOYMENT_ENV\" ]]; then
                DEPLOYMENT_ENV=\"\${WIZARD_ENV^^}\"
            fi
            if [[ -z \"\$TAG\" && \"\$WIZARD_ENV\" == *-* ]]; then
                TAG=\"\${WIZARD_ENV##*-}\"
                TAG=\"\${TAG^^}\"
            fi
        }

        derive_env_defaults
        echo \"DEP=\$DEPLOYMENT_ENV\"
        echo \"TAG=\$TAG\"
    "
}

@test "derive_env_defaults: test-qa2 → DEPLOYMENT_ENV=TEST-QA2, TAG=QA2" {
    result=$(_run_derive "test-qa2")
    [[ "$result" == *"DEP=TEST-QA2"* ]]
    [[ "$result" == *"TAG=QA2"* ]]
}

@test "derive_env_defaults: dev-094 → DEPLOYMENT_ENV=DEV-094, TAG=094" {
    result=$(_run_derive "dev-094")
    [[ "$result" == *"DEP=DEV-094"* ]]
    [[ "$result" == *"TAG=094"* ]]
}

@test "derive_env_defaults: production → DEPLOYMENT_ENV=PRODUCTION, TAG empty" {
    result=$(_run_derive "production")
    [[ "$result" == *"DEP=PRODUCTION"* ]]
    tag_line=$(echo "$result" | grep "^TAG=")
    [ "$tag_line" = "TAG=" ]
}

@test "derive_env_defaults: prod-tenant-a → DEPLOYMENT_ENV=PROD-TENANT-A, TAG=A" {
    result=$(_run_derive "prod-tenant-a")
    [[ "$result" == *"DEP=PROD-TENANT-A"* ]]
    [[ "$result" == *"TAG=A"* ]]
}

@test "derive_env_defaults: existing DEPLOYMENT_ENV not overwritten" {
    result=$(_run_derive "test-qa2" "CUSTOM" "")
    [[ "$result" == *"DEP=CUSTOM"* ]]
}

@test "derive_env_defaults: existing TAG not overwritten" {
    result=$(_run_derive "test-qa2" "" "MYTAG")
    [[ "$result" == *"TAG=MYTAG"* ]]
}

##region Library Integration Tests

@test "wizard sources lib.sh successfully" {
    run bash -c "source scripts/deploy/lib.sh && source scripts/deploy/interactive_wizard.sh --env=test 2>&1 | head -1"
    # Should not error on sourcing
    [[ "$output" != *"command not found"* ]] || [ "$status" -eq 0 ]
}

##endregion

##region Manual Mode Auto-sets skip_confirm and no_dep

# Helper: simulate phase2 option prompts in a subshell.
# Args: manual_answer skip_confirm_answer no_dep_answer
# Outputs: "MANUAL=<0|1> SKIP=<0|1> NODEP=<0|1>"
_run_phase2_options() {
    local manual_ans="$1"
    local skip_ans="${2:-n}"    # only used when manual=n
    local nodep_ans="${3:-n}"   # only used when manual=n

    bash -c "
        MANUAL_MODE=0
        SKIP_CONFIRM=0
        NO_DEP=0

        prompt_yesno() {
            local question=\"\$1\"
            if [[ \"\$question\" == *'manual mode'* ]]; then
                [[ '$manual_ans' == 'y' ]] && return 0 || return 1
            fi
            if [[ \"\$question\" == *'confirmation'* ]]; then
                [[ '$skip_ans' == 'y' ]] && return 0 || return 1
            fi
            if [[ \"\$question\" == *'bizevents'* ]]; then
                [[ '$nodep_ans' == 'y' ]] && return 0 || return 1
            fi
            return 1
        }
        log_info() { :; }

        if prompt_yesno 'Generate SQL only (manual mode)?' 'n'; then
            MANUAL_MODE=1
            SKIP_CONFIRM=1
            NO_DEP=1
            log_info 'Manual mode enabled — skipping confirmation and bizevents prompts (not applicable)'
        else
            if prompt_yesno 'Skip deployment confirmation?' 'n'; then
                SKIP_CONFIRM=1
            fi
            if prompt_yesno 'Skip deployment bizevents?' 'n'; then
                NO_DEP=1
            fi
        fi

        echo \"MANUAL=\$MANUAL_MODE SKIP=\$SKIP_CONFIRM NODEP=\$NO_DEP\"
    "
}

@test "manual mode auto-sets skip_confirm=1" {
    result=$(_run_phase2_options "y")
    [[ "$result" == *"MANUAL=1"* ]]
    [[ "$result" == *"SKIP=1"* ]]
}

@test "manual mode auto-sets no_dep=1" {
    result=$(_run_phase2_options "y")
    [[ "$result" == *"MANUAL=1"* ]]
    [[ "$result" == *"NODEP=1"* ]]
}

@test "manual mode does not prompt for skip_confirm separately" {
    # When manual=y, skip_confirm answer is irrelevant — result must still be SKIP=1
    result=$(_run_phase2_options "y" "n")
    [[ "$result" == *"SKIP=1"* ]]
}

@test "manual mode does not prompt for no_dep separately" {
    # When manual=y, no_dep answer is irrelevant — result must still be NODEP=1
    result=$(_run_phase2_options "y" "n" "n")
    [[ "$result" == *"NODEP=1"* ]]
}

@test "non-manual mode: skip_confirm=n leaves SKIP=0" {
    result=$(_run_phase2_options "n" "n")
    [[ "$result" == *"MANUAL=0"* ]]
    [[ "$result" == *"SKIP=0"* ]]
}

@test "non-manual mode: skip_confirm=y sets SKIP=1" {
    result=$(_run_phase2_options "n" "y")
    [[ "$result" == *"MANUAL=0"* ]]
    [[ "$result" == *"SKIP=1"* ]]
}

@test "non-manual mode: no_dep=n leaves NODEP=0" {
    result=$(_run_phase2_options "n" "n" "n")
    [[ "$result" == *"MANUAL=0"* ]]
    [[ "$result" == *"NODEP=0"* ]]
}

@test "non-manual mode: no_dep=y sets NODEP=1" {
    result=$(_run_phase2_options "n" "n" "y")
    [[ "$result" == *"MANUAL=0"* ]]
    [[ "$result" == *"NODEP=1"* ]]
}

##endregion

##region Phase 3 Skip Condition

# Helper: run the phase3 skip-check logic in a subshell.
# Args: scope manual_mode
# Outputs: "SKIPPED" or "RAN"
_run_phase3_skip_check() {
    local scope="$1"
    local manual="$2"

    bash -c "
        DEPLOYMENT_SCOPE='$scope'
        MANUAL_MODE='$manual'

        log_info() { :; }

        if ! [[ \"\$DEPLOYMENT_SCOPE\" =~ (all|setup|plugins|agents|config) ]]; then
            log_info 'Skipping Phase 3 (plugin selection not applicable for this scope)'
            echo 'SKIPPED'
        else
            echo 'RAN'
        fi
    "
}

@test "phase3: scope=all runs (manual=0)" {
    result=$(_run_phase3_skip_check "all" "0")
    [ "$result" = "RAN" ]
}

@test "phase3: scope=all runs (manual=1 — manual mode must not skip)" {
    result=$(_run_phase3_skip_check "all" "1")
    [ "$result" = "RAN" ]
}

@test "phase3: scope=setup runs" {
    result=$(_run_phase3_skip_check "setup" "0")
    [ "$result" = "RAN" ]
}

@test "phase3: scope=plugins runs" {
    result=$(_run_phase3_skip_check "plugins" "0")
    [ "$result" = "RAN" ]
}

@test "phase3: scope=agents runs" {
    result=$(_run_phase3_skip_check "agents" "0")
    [ "$result" = "RAN" ]
}

@test "phase3: scope=config runs" {
    result=$(_run_phase3_skip_check "config" "0")
    [ "$result" = "RAN" ]
}

@test "phase3: scope=init skipped" {
    result=$(_run_phase3_skip_check "init" "0")
    [ "$result" = "SKIPPED" ]
}

@test "phase3: scope=admin skipped" {
    result=$(_run_phase3_skip_check "admin" "0")
    [ "$result" = "SKIPPED" ]
}

@test "phase3: scope=upgrade skipped" {
    result=$(_run_phase3_skip_check "upgrade" "0")
    [ "$result" = "SKIPPED" ]
}

@test "phase3: scope=teardown skipped" {
    result=$(_run_phase3_skip_check "teardown" "0")
    [ "$result" = "SKIPPED" ]
}

@test "phase3: scope=dt_assets skipped" {
    result=$(_run_phase3_skip_check "dt_assets" "0")
    [ "$result" = "SKIPPED" ]
}

@test "phase3: scope=apikey skipped" {
    result=$(_run_phase3_skip_check "apikey" "0")
    [ "$result" = "SKIPPED" ]
}

##endregion

##region prompt_select_one Empty-Input Default

# Helper: run prompt_select_one with piped input in a subshell.
# Args: input_str default_option options...
# Outputs: selected option text
_run_select_one() {
    local input_str="$1"
    shift
    local default_opt="$1"
    shift
    local opts=("$@")

    # Build quoted options list for bash -c
    local opts_str=""
    for o in "${opts[@]}"; do
        opts_str+="\"$o\" "
    done

    bash -c "
        source scripts/deploy/lib.sh
        echo '$input_str' | prompt_select_one 'Pick:' '$default_opt' $opts_str
    " 2>/dev/null
}

@test "prompt_select_one: empty input selects default option" {
    result=$(_run_select_one "" "WARN" "DEBUG" "INFO" "WARN" "ERROR")
    [ "$result" = "WARN" ]
}

@test "prompt_select_one: empty input selects first-position default" {
    result=$(_run_select_one "" "DEBUG" "DEBUG" "INFO" "WARN" "ERROR")
    [ "$result" = "DEBUG" ]
}

@test "prompt_select_one: numeric input selects correct option" {
    result=$(_run_select_one "2" "WARN" "DEBUG" "INFO" "WARN" "ERROR")
    [ "$result" = "INFO" ]
}

@test "prompt_select_one: numeric input for default option works" {
    result=$(_run_select_one "3" "WARN" "DEBUG" "INFO" "WARN" "ERROR")
    [ "$result" = "WARN" ]
}

##endregion

##region deploy_disabled_plugins Prompt (Phase 3)

# Helper: simulate Phase 3 Q2 logic in a subshell.
# Args: plugins_mode yesno_answer (y/n)
# Outputs: "DEPLOY_DISABLED=<0|1>"
_run_phase3_deploy_disabled() {
    local mode="$1"
    local ans="$2"

    bash -c "
        PLUGINS_MODE='$mode'
        DEPLOY_DISABLED_PLUGINS=1

        prompt_yesno() {
            [[ '$ans' == 'y' ]] && return 0 || return 1
        }
        log_ok() { :; }

        if [[ \"\$PLUGINS_MODE\" == 'all' ]]; then
            DEPLOY_DISABLED_PLUGINS=1
        else
            if prompt_yesno 'Deploy all plugin code (including disabled)?' 'y'; then
                DEPLOY_DISABLED_PLUGINS=1
            else
                DEPLOY_DISABLED_PLUGINS=0
            fi
        fi

        echo \"DEPLOY_DISABLED=\$DEPLOY_DISABLED_PLUGINS\"
    "
}

@test "deploy_disabled_plugins: mode=all silently sets 1 (no prompt)" {
    result=$(_run_phase3_deploy_disabled "all" "n")
    [[ "$result" == *"DEPLOY_DISABLED=1"* ]]
}

@test "deploy_disabled_plugins: mode=none answer=y sets 1" {
    result=$(_run_phase3_deploy_disabled "none" "y")
    [[ "$result" == *"DEPLOY_DISABLED=1"* ]]
}

@test "deploy_disabled_plugins: mode=none answer=n sets 0" {
    result=$(_run_phase3_deploy_disabled "none" "n")
    [[ "$result" == *"DEPLOY_DISABLED=0"* ]]
}

@test "deploy_disabled_plugins: mode=selected answer=n sets 0" {
    result=$(_run_phase3_deploy_disabled "selected" "n")
    [[ "$result" == *"DEPLOY_DISABLED=0"* ]]
}

##endregion

##region config_persistence Save Options

# Helper: simulate config_persistence option list in a subshell.
# Args: existing_config (path or empty)
# Outputs: space-separated list of option labels shown
_run_persistence_options() {
    local existing="$1"

    bash -c "
        EXISTING_CONFIG='$existing'

        if [[ -n \"\$EXISTING_CONFIG\" ]]; then
            echo 'Save as new config'
            echo 'Update existing config'
            echo 'Print to stdout only'
            echo 'Discard'
        else
            echo 'Save config'
            echo 'Print to stdout only'
            echo 'Discard'
        fi
    "
}

@test "config_persistence: no existing config omits 'Update existing config'" {
    result=$(_run_persistence_options "")
    [[ "$result" != *"Update existing config"* ]]
    [[ "$result" == *"Save config"* ]]
}

@test "config_persistence: no existing config shows 3 options" {
    result=$(_run_persistence_options "")
    count=$(echo "$result" | wc -l | tr -d ' ')
    [ "$count" -eq 3 ]
}

@test "config_persistence: existing config shows 'Update existing config'" {
    result=$(_run_persistence_options "/some/config.yml")
    [[ "$result" == *"Update existing config"* ]]
    [[ "$result" == *"Save as new config"* ]]
}

@test "config_persistence: existing config shows 4 options" {
    result=$(_run_persistence_options "/some/config.yml")
    count=$(echo "$result" | wc -l | tr -d ' ')
    [ "$count" -eq 4 ]
}

##endregion

##region Summary Display

# Helper: simulate the summary Deploy Disabled Code line.
# Args: deploy_disabled_plugins value (0 or 1)
_run_summary_disabled_display() {
    local val="$1"
    bash -c "
        DEPLOY_DISABLED_PLUGINS=$val
        echo \"\$( [[ \"\$DEPLOY_DISABLED_PLUGINS\" -eq 1 ]] && echo 'YES' || echo 'NO' )\"
    "
}

@test "summary: DEPLOY_DISABLED_PLUGINS=1 displays YES" {
    result=$(_run_summary_disabled_display 1)
    [ "$result" = "YES" ]
}

@test "summary: DEPLOY_DISABLED_PLUGINS=0 displays NO" {
    result=$(_run_summary_disabled_display 0)
    [ "$result" = "NO" ]
}

##endregion

##region seed_defaults_from_config

@test "seed_defaults_from_config: reads LOG_LEVEL from default config" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        DEFAULT_CONFIG='build/config-default.yml'
        read_default() {
            local key_path=\"\$1\" fallback=\"\$2\"
            if [[ ! -f \"\$DEFAULT_CONFIG\" ]] || ! command -v yq >/dev/null 2>&1; then
                echo \"\$fallback\"; return 0
            fi
            local val
            val=\$(yq eval \".\${key_path}\" \"\$DEFAULT_CONFIG\" 2>/dev/null || true)
            if [[ -z \"\$val\" || \"\$val\" == 'null' ]]; then echo \"\$fallback\"; else echo \"\$val\"; fi
        }
        LOG_LEVEL=\$(read_default 'core.log_level' 'WARN')
        echo \"LOG_LEVEL=\$LOG_LEVEL\"
    " 2>/dev/null)
    [[ "$result" == *"LOG_LEVEL=WARN"* ]]
}

@test "seed_defaults_from_config: reads PROCEDURE_TIMEOUT from default config" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        DEFAULT_CONFIG='build/config-default.yml'
        read_default() {
            local key_path=\"\$1\" fallback=\"\$2\"
            if [[ ! -f \"\$DEFAULT_CONFIG\" ]] || ! command -v yq >/dev/null 2>&1; then
                echo \"\$fallback\"; return 0
            fi
            local val
            val=\$(yq eval \".\${key_path}\" \"\$DEFAULT_CONFIG\" 2>/dev/null || true)
            if [[ -z \"\$val\" || \"\$val\" == 'null' ]]; then echo \"\$fallback\"; else echo \"\$val\"; fi
        }
        PROCEDURE_TIMEOUT=\$(read_default 'core.procedure_timeout' '3600')
        echo \"TIMEOUT=\$PROCEDURE_TIMEOUT\"
    " 2>/dev/null)
    [[ "$result" == *"TIMEOUT=3600"* ]]
}

@test "seed_defaults_from_config: falls back when default config absent" {
    result=$(bash -c "
        DEFAULT_CONFIG='/nonexistent/config.yml'
        read_default() {
            local key_path=\"\$1\" fallback=\"\$2\"
            if [[ ! -f \"\$DEFAULT_CONFIG\" ]]; then echo \"\$fallback\"; return 0; fi
            echo \"\$fallback\"
        }
        LOG_LEVEL=\$(read_default 'core.log_level' 'WARN')
        echo \"LOG_LEVEL=\$LOG_LEVEL\"
    " 2>/dev/null)
    [[ "$result" == *"LOG_LEVEL=WARN"* ]]
}

##endregion

##region Phase 5 OTel Config

# Helper: simulate phase5 OTel collection in a subshell.
# Args: input values for logs/spans/metrics/events/biz_events/max_fails (empty = accept default)
# Outputs: "LOGS=<val> SPANS=<val> METRICS=<val> EVENTS=<val> BIZ=<val> FAILS=<val>"
_run_phase5_otel() {
    local in_logs="${1:-}"
    local in_spans="${2:-}"
    local in_metrics="${3:-}"
    local in_events="${4:-}"
    local in_biz="${5:-}"
    local in_fails="${6:-}"

    bash -c "
        OTEL_LOGS_DISABLED=''
        OTEL_SPANS_DISABLED=''
        OTEL_METRICS_DISABLED=''
        OTEL_EVENTS_DISABLED=''
        OTEL_BIZ_EVENTS_DISABLED=''
        OTEL_MAX_CONSECUTIVE_API_FAILS=''

        def_logs='false'; def_spans='false'; def_metrics='false'
        def_events='false'; def_biz='false'; def_fails='10'

        process() {
            local varname=\"\$1\" def=\"\$2\" inp=\"\$3\"
            [[ -z \"\$inp\" ]] && inp=\"\$def\"
            [[ \"\$inp\" != \"\$def\" ]] && eval \"\$varname=\$inp\"
        }

        process OTEL_LOGS_DISABLED    \"\$def_logs\"    '$in_logs'
        process OTEL_SPANS_DISABLED   \"\$def_spans\"   '$in_spans'
        process OTEL_METRICS_DISABLED \"\$def_metrics\" '$in_metrics'
        process OTEL_EVENTS_DISABLED  \"\$def_events\"  '$in_events'
        process OTEL_BIZ_EVENTS_DISABLED \"\$def_biz\"  '$in_biz'
        process OTEL_MAX_CONSECUTIVE_API_FAILS \"\$def_fails\" '$in_fails'

        echo \"LOGS=\${OTEL_LOGS_DISABLED:-default}\"
        echo \"SPANS=\${OTEL_SPANS_DISABLED:-default}\"
        echo \"METRICS=\${OTEL_METRICS_DISABLED:-default}\"
        echo \"EVENTS=\${OTEL_EVENTS_DISABLED:-default}\"
        echo \"BIZ=\${OTEL_BIZ_EVENTS_DISABLED:-default}\"
        echo \"FAILS=\${OTEL_MAX_CONSECUTIVE_API_FAILS:-default}\"
    "
}

@test "phase5 otel: all defaults accepted — no overrides stored" {
    result=$(_run_phase5_otel "" "" "" "" "" "")
    [[ "$result" == *"LOGS=default"* ]]
    [[ "$result" == *"SPANS=default"* ]]
    [[ "$result" == *"METRICS=default"* ]]
    [[ "$result" == *"EVENTS=default"* ]]
    [[ "$result" == *"BIZ=default"* ]]
    [[ "$result" == *"FAILS=default"* ]]
}

@test "phase5 otel: disabling events stores override" {
    result=$(_run_phase5_otel "" "" "" "true" "" "")
    [[ "$result" == *"EVENTS=true"* ]]
    [[ "$result" == *"LOGS=default"* ]]
}

@test "phase5 otel: disabling biz_events stores override" {
    result=$(_run_phase5_otel "" "" "" "" "true" "")
    [[ "$result" == *"BIZ=true"* ]]
}

@test "phase5 otel: changing max_consecutive_api_fails stores override" {
    result=$(_run_phase5_otel "" "" "" "" "" "5")
    [[ "$result" == *"FAILS=5"* ]]
}

@test "phase5 otel: accepting default max_fails stores no override" {
    result=$(_run_phase5_otel "" "" "" "" "" "10")
    [[ "$result" == *"FAILS=default"* ]]
}

##endregion

##region Plugin Customization

@test "customize_plugins: wizard script has valid bash syntax after changes" {
    run bash -n scripts/deploy/interactive_wizard.sh
    [ "$status" -eq 0 ]
}

@test "customize_plugins: phase3 calls customize when answer=y (smoke)" {
    # Verify the function exists in the wizard source
    grep -q "customize_plugins_interactive" scripts/deploy/interactive_wizard.sh
}

@test "customize_plugins: known plugins list includes event_log and query_history" {
    grep -q "event_log" scripts/deploy/interactive_wizard.sh
    grep -q "query_history" scripts/deploy/interactive_wizard.sh
}

##endregion

##region Plugin Checklist Order

@test "phase3 plugin checklist is in alphabetical order (dynamic discovery)" {
    # discover_plugin_names must return sorted output
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        discover_plugin_names
    ")
    sorted=$(echo "$result" | sort)
    [ "$result" = "$sorted" ]
}

@test "phase3 plugin checklist starts with active_queries (dynamic discovery)" {
    # Requires build artifacts — skip if build/ not populated
    [[ -f "build/config-default.yml" || -d "build/30_plugins" ]] || skip "build artifacts not present"
    first=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        discover_plugin_names | head -1
    ")
    [ "$first" = "active_queries" ]
}

@test "phase3 plugin checklist ends with warehouse_usage (dynamic discovery)" {
    # Requires build artifacts — skip if build/ not populated
    [[ -f "build/config-default.yml" || -d "build/30_plugins" ]] || skip "build artifacts not present"
    last=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        discover_plugin_names | tail -1
    ")
    [ "$last" = "warehouse_usage" ]
}

@test "discover_plugins matches build artifacts" {
    # Requires build artifacts — skip if build/ not populated
    [[ -f "build/config-default.yml" || -d "build/30_plugins" ]] || skip "build artifacts not present"
    # Wizard's discover_plugin_names must return exactly the same set as build/30_plugins/
    wizard_list=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        discover_plugin_names
    ")
    build_list=$(find build/30_plugins -maxdepth 1 -name '*.sql' -print0 2>/dev/null | xargs -0 -n1 basename | sed 's/\.sql$//' | sort)
    [ "$wizard_list" = "$build_list" ]
}

@test "discover_plugins falls back to build/30_plugins when config-default.yml absent" {
    # Simulate environment where config-default.yml does not exist.
    # discover_plugin_names must fall back to build/30_plugins/*.sql basenames.
    result=$(bash -c "
        # Create a temp workspace mimicking a build without config-default.yml
        tmpdir=\$(mktemp -d)
        mkdir -p \"\$tmpdir/build/30_plugins\"
        touch \"\$tmpdir/build/30_plugins/active_queries.sql\"
        touch \"\$tmpdir/build/30_plugins/warehouse_usage.sql\"
        touch \"\$tmpdir/build/30_plugins/query_history.sql\"

        # Inline the fallback logic (mirrors the implementation)
        root=\"\$tmpdir\"
        build_plugins_dir=\"\${root}/build/30_plugins\"

        # No config-default.yml → skip primary, use fallback
        if [[ -d \"\$build_plugins_dir\" ]]; then
            for f in \"\$build_plugins_dir\"/*.sql; do
                [[ -f \"\$f\" ]] || continue
                basename \"\$f\" .sql
            done | sort
        fi
        rm -rf \"\$tmpdir\"
    ")
    # Must return a non-empty list
    [ -n "$result" ]
    # Must include known plugins
    echo "$result" | grep -q "active_queries"
    echo "$result" | grep -q "warehouse_usage"
    # Must be sorted
    sorted=$(echo "$result" | sort)
    [ "$result" = "$sorted" ]
}

##endregion

##region stdout path Continue-to-deployment prompt

@test "config_persistence: stdout path prompts to continue to deployment" {
    grep -q "Continue to deployment?" scripts/deploy/interactive_wizard.sh
}

@test "config_persistence: stdout path returns 0 when user says yes to continue" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true

        # Override generate_config_yaml to be a no-op
        generate_config_yaml() { :; }

        # Override prompt_yesno: 'Continue to deployment?' → yes
        prompt_yesno() {
            [[ \"\$1\" == *'Continue to deployment'* ]] && return 0
            return 1
        }

        # Simulate the stdout branch directly
        echo '' >&2
        if prompt_yesno 'Config printed above. Continue to deployment?' 'n'; then
            echo 'CONTINUE'
        else
            echo 'EXIT'
        fi
    " 2>/dev/null)
    [[ "$result" == *"CONTINUE"* ]]
}

@test "config_persistence: stdout path returns 1 when user says no to continue" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true

        prompt_yesno() {
            [[ \"\$1\" == *'Continue to deployment'* ]] && return 1
            return 1
        }

        echo '' >&2
        if prompt_yesno 'Config printed above. Continue to deployment?' 'n'; then
            echo 'CONTINUE'
        else
            echo 'EXIT'
        fi
    " 2>/dev/null)
    [[ "$result" == *"EXIT"* ]]
}

##endregion


@test "bool_to_yaml: 1 → true" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml 1")
    [ "$result" = "true" ]
}

@test "bool_to_yaml: 0 → false" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml 0")
    [ "$result" = "false" ]
}

@test "bool_to_yaml: true → true" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml true")
    [ "$result" = "true" ]
}

@test "bool_to_yaml: false → false" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml false")
    [ "$result" = "false" ]
}

@test "bool_to_yaml: yes → true" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml yes")
    [ "$result" = "true" ]
}

@test "bool_to_yaml: no → false" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml no")
    [ "$result" = "false" ]
}

@test "bool_to_yaml: TRUE (uppercase) → true" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml TRUE")
    [ "$result" = "true" ]
}

@test "bool_to_yaml: FALSE (uppercase) → false" {
    result=$(bash -c "source scripts/deploy/lib.sh; bool_to_yaml FALSE")
    [ "$result" = "false" ]
}

##endregion

##region generate_config_yaml YAML Boolean Output

@test "generate_config_yaml: DEPLOY_DISABLED_PLUGINS=1 writes 'true' not '1'" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        DEPLOY_DISABLED_PLUGINS=1
        echo \"deploy_disabled_plugins: \$(bool_to_yaml \$DEPLOY_DISABLED_PLUGINS)\"
    " 2>/dev/null)
    [[ "$result" == *"deploy_disabled_plugins: true"* ]]
    [[ "$result" != *"deploy_disabled_plugins: 1"* ]]
}

@test "generate_config_yaml: DEPLOY_DISABLED_PLUGINS=0 writes 'false' not '0'" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        DEPLOY_DISABLED_PLUGINS=0
        echo \"deploy_disabled_plugins: \$(bool_to_yaml \$DEPLOY_DISABLED_PLUGINS)\"
    " 2>/dev/null)
    [[ "$result" == *"deploy_disabled_plugins: false"* ]]
    [[ "$result" != *"deploy_disabled_plugins: 0"* ]]
}

@test "generate_config_yaml: plugin is_disabled override normalised to YAML bool" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        k='is_disabled'; v='1'
        case \"\$k\" in
            is_disabled|disabled_by_default) v=\$(bool_to_yaml \"\$v\") ;;
        esac
        echo \"\$k: \$v\"
    " 2>/dev/null)
    [[ "$result" == *"is_disabled: true"* ]]
    [[ "$result" != *"is_disabled: 1"* ]]
}

@test "generate_config_yaml: otel is_disabled normalised via bool_to_yaml" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        OTEL_EVENTS_DISABLED='true'
        echo \"is_disabled: \$(bool_to_yaml \"\$OTEL_EVENTS_DISABLED\")\"
    " 2>/dev/null)
    [[ "$result" == *"is_disabled: true"* ]]
}

##endregion

##region read_default Uses build/config-default.yml Only

@test "read_default: returns value from build/config-default.yml" {
    # When config-default.yml exists, read_default must return the value from it.
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        if [[ ! -f \"\$DEFAULT_CONFIG\" ]]; then
            echo 'SKIP'
            exit 0
        fi
        read_default 'plugins.active_queries.schedule' ''
    " 2>/dev/null)
    # Either SKIP (no build yet) or a non-empty CRON expression
    [[ "$result" == "SKIP" || "$result" == *"CRON"* ]]
}

@test "read_default: returns fallback when config-default.yml absent" {
    # When config-default.yml does not exist, read_default must return the fallback.
    # It must NOT fall back to src/ plugin config files.
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        DEFAULT_CONFIG='/nonexistent/config-default.yml'
        read_default 'plugins.active_queries.schedule' 'MY_FALLBACK'
    " 2>/dev/null)
    [ "$result" = "MY_FALLBACK" ]
}

@test "read_default: returns fallback for unknown key" {
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        read_default 'plugins.active_queries.nonexistent_key' 'FALLBACK'
    " 2>/dev/null)
    [ "$result" = "FALLBACK" ]
}

@test "read_default: config-default.yml is single source of truth" {
    # Verify read_default does NOT read from src/dtagent/plugins/ config files
    result=$(bash -c "
        source scripts/deploy/lib.sh
        source scripts/deploy/interactive_wizard.sh 2>/dev/null || true
        DEFAULT_CONFIG='/nonexistent/config-default.yml'
        # Even though src/ plugin configs exist, fallback must be returned
        read_default 'plugins.active_queries.fast_mode' 'NOPE'
    " 2>/dev/null)
    [ "$result" = "NOPE" ]
}

##endregion
