#!/usr/bin/env bats

# Tests for scripts/deploy/interactive_wizard.sh

setup() {
    # shellcheck disable=SC2154
    cd "$BATS_TEST_DIRNAME/../.." || exit 1
}

##region Argument Parsing Tests

@test "wizard requires --env argument" {
    run scripts/deploy/interactive_wizard.sh
    [ "$status" -ne 0 ]
    [[ "$output" == *"--env is required"* ]]
}

@test "wizard script is executable" {
    [ -x scripts/deploy/interactive_wizard.sh ]
}

@test "wizard script has valid bash syntax" {
    run bash -n scripts/deploy/interactive_wizard.sh
    [ "$status" -eq 0 ]
}

##endregion

##region Config Generation Tests

@test "wizard generates valid YAML structure" {
    # Create a temporary directory for test
    local test_dir
    test_dir=$(mktemp -d)
    cd "$test_dir"
    mkdir -p conf

    # Create a simple test that just checks the config generation function
    # by sourcing the lib and defining the function directly
    source "$BATS_TEST_DIRNAME/../../scripts/deploy/lib.sh"

    # Set up test variables
    DT_TENANT="test.live.dynatrace.com"
    DT_TOKEN="token123"
    SF_ACCOUNT="org-account"
    DEPLOYMENT_ENV="test-env"
    TAG="test-tag"
    LOG_LEVEL="WARN"
    PROCEDURE_TIMEOUT="3600"
    DEPLOY_DISABLED_PLUGINS=1

    # Define the generate_config_yaml function (from wizard)
    generate_config_yaml() {
        local output_file="$1"

        # Create YAML structure
        cat > "$output_file" << EOFYAML
# DSOA Configuration - Generated by interactive wizard
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

core:
  dynatrace_tenant_address: "$DT_TENANT"
  snowflake:
    account_name: "$SF_ACCOUNT"
  deployment_environment: "$DEPLOYMENT_ENV"
  log_level: "$LOG_LEVEL"
  procedure_timeout: $PROCEDURE_TIMEOUT
EOFYAML

        if [[ -n "$TAG" ]]; then
            echo "  tag: \"$TAG\"" >> "$output_file"
        fi
    }

    # Test config generation
    local config_file="$test_dir/test-config.yml"
    generate_config_yaml "$config_file"

    # Verify file was created
    [ -f "$config_file" ]

    # Verify it contains expected keys
    grep -q "dynatrace_tenant_address" "$config_file"
    grep -q "snowflake" "$config_file"
    grep -q "deployment_environment" "$config_file"
    grep -q "test.live.dynatrace.com" "$config_file"

    cd - > /dev/null
    rm -rf "$test_dir"
}

##endregion

##region Library Integration Tests

@test "wizard sources lib.sh successfully" {
    run bash -c "source scripts/deploy/lib.sh && source scripts/deploy/interactive_wizard.sh --env=test 2>&1 | head -1"
    # Should not error on sourcing
    [[ "$output" != *"command not found"* ]] || [ "$status" -eq 0 ]
}

##endregion

