#!/usr/bin/env python3
"""Generate .context/devlog/1.0.1/display-name-review.md from all instruments-def.yml files.

Usage: python3 scripts/tools/generate_display_name_review.py
"""

import glob
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent.parent
OUTPUT = REPO_ROOT / ".context/devlog/1.0.1/display-name-review.md"

SECTION_ORDER = {"attribute": 0, "dimension": 1, "event_timestamp": 2, "metric": 3}
PLURAL_TO_SINGULAR = {
    "attributes": "attribute",
    "dimensions": "dimension",
    "event_timestamps": "event_timestamp",
    "metrics": "metric",
}
EXISTING_SEMDICT = {"ref", "otel-only", "deprecated-alias"}


def plugin_name(path: str) -> str:
    parts = path.split("/")
    if "dtagent.conf" in parts:
        return "dtagent.conf"
    return parts[-2].replace(".config", "")


def truncate(text: str, limit: int = 110) -> str:
    text = str(text).replace("\n", " ").strip()
    return text if len(text) <= limit else text[:limit].rstrip() + "…"


def collect_rows(files: list[str]) -> list[dict]:
    rows = []
    for f in sorted(files):
        with open(f) as fh:
            data = yaml.safe_load(fh)
        if not isinstance(data, dict):
            continue
        plugin = plugin_name(f)
        for section, field_type in PLURAL_TO_SINGULAR.items():
            entries = data.get(section) or {}
            for key, entry in entries.items():
                if not isinstance(entry, dict):
                    continue
                semdict = entry.get("__semdict", "new")
                rows.append(
                    {
                        "field": key,
                        "type": field_type,
                        "plugin": plugin,
                        "displayName": entry.get("displayName", ""),
                        "description": truncate(entry.get("__description", "")),
                        "semdict": semdict,
                        "origin": "existing" if semdict in EXISTING_SEMDICT else "dsoa",
                    }
                )
    return rows


def table_header() -> str:
    return (
        "| Field | displayName | Description | Type | Plugin |\n"
        "| --- | --- | --- | --- | --- |\n"
    )


def table_row(r: dict) -> str:
    return (
        f"| `{r['field']}` | {r['displayName']} | {r['description']} "
        f"| {r['type']} | {r['plugin']} |\n"
    )


def sort_key(r: dict) -> tuple:
    return (r["field"].lower(), r["plugin"].lower())


def render(rows: list[dict]) -> str:
    dsoa = sorted([r for r in rows if r["origin"] == "dsoa"], key=sort_key)
    existing = sorted([r for r in rows if r["origin"] == "existing"], key=sort_key)

    out = [
        "---\n",
        "cssclasses:\n",
        "  - wide-page\n",
        "---\n",
        "# displayName Review — BIZOBS-2639\n\n",
        "Review document for `displayName` values across all 21 `instruments-def.yml` files. "
        "Entries split by origin: fields newly introduced by DSOA vs. fields that reference "
        "existing Dynatrace Semantic Dictionary or OTel semconv definitions.\n\n",
        f"*Generated by `scripts/tools/generate_display_name_review.py` — "
        f"{len(dsoa)} DSOA fields, {len(existing)} pre-existing fields.*\n\n",
        "---\n\n",
        "## Fields introduced by DSOA\n\n",
        "Fields with `__semdict: new` (or no `__semdict`). "
        "These did not exist in the Semantic Dictionary before DSOA.\n\n",
        table_header(),
    ]
    for r in dsoa:
        out.append(table_row(r))

    out += [
        "\n---\n\n",
        "## Fields referenced from existing standards\n\n",
        "Fields with `__semdict: ref`, `otel-only`, or `deprecated-alias`. "
        "These existed in the Dynatrace SD or OTel semconv before DSOA.\n\n",
        table_header(),
    ]
    for r in existing:
        out.append(table_row(r))

    return "".join(out)


def main():
    files = glob.glob(str(REPO_ROOT / "src/dtagent/plugins/*/instruments-def.yml"))
    files += glob.glob(str(REPO_ROOT / "src/dtagent.conf/instruments-def.yml"))
    if not files:
        print("No instruments-def.yml files found.", file=sys.stderr)
        sys.exit(1)

    rows = collect_rows(files)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(rows))
    dsoa = sum(1 for r in rows if r["origin"] == "dsoa")
    existing = sum(1 for r in rows if r["origin"] == "existing")
    print(f"Written {OUTPUT} — {dsoa} DSOA + {existing} existing = {dsoa + existing} rows")


if __name__ == "__main__":
    main()
