-- ============================================================================
-- Metering plugin test setup for DSOA telemetry validation
-- Exercises: metering metrics across multiple service types (BDX-1865)
--
-- Coverage:
--   C2.11 — Metering metrics across >=3 service types
--   C3.7  — Metering logs include service_type dimension
--   C8.4  — event_usage plugin deprecated — no new telemetry
--
-- Strategy:
--   The metering plugin reads from SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
--   which records credit consumption by service type. Service types include:
--     - AUTO_CLUSTERING
--     - MATERIALIZED_VIEW
--     - SEARCH_OPTIMIZATION
--     - SERVERLESS_TASK
--     - SNOWPIPE / SNOWPIPE_STREAMING
--     - QUERY_ACCELERATION
--     - REPLICATION
--
--   Most of these are automatically generated by Snowflake when the relevant
--   features are active. We create objects that trigger multiple service types:
--     1. A clustered table (triggers AUTO_CLUSTERING metering)
--     2. A materialized view (triggers MATERIALIZED_VIEW metering)
--     3. A serverless task (triggers SERVERLESS_TASK metering)
--
--   NOTE: METERING_HISTORY has 1-3h latency. These objects need to run for
--   at least one billing cycle to appear in METERING_HISTORY.
--
-- Prerequisites:
--   - DTAGENT_QA_OWNER role must exist
--   - DSOA_TEST_DB must exist
--   - metering plugin must be enabled (is_enabled: true)
--   - event_usage plugin must be DISABLED (BDX-1865 deprecated it)
--
-- Cost: minimal (serverless task + auto-clustering = ~0.01-0.05 credits/hour)
--
-- HOW TO RUN:
--   snow sql --connection snow_agent_test-qa -f test/tools/setup_test_metering.sql
-- ============================================================================

-- ============================================================================
-- 1. Setup
-- ============================================================================
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE DTAGENT_QA_OWNER;

USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS DSOA_TEST_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'Shared warehouse for DSOA synthetic test setups';
GRANT USAGE ON WAREHOUSE DSOA_TEST_WH TO ROLE DTAGENT_QA_OWNER;

USE ROLE DTAGENT_QA_OWNER;
USE WAREHOUSE DSOA_TEST_WH;

CREATE SCHEMA IF NOT EXISTS DSOA_TEST_DB.METERING_TEST;
USE SCHEMA DSOA_TEST_DB.METERING_TEST;

-- ============================================================================
-- 2. AUTO_CLUSTERING — clustered table with ongoing inserts
--    Auto-clustering runs when data is inserted out of cluster-key order.
-- ============================================================================
CREATE OR REPLACE TABLE DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG (
    LOG_ID      NUMBER        NOT NULL,
    LOG_LEVEL   VARCHAR(10)   NOT NULL,
    MODULE      VARCHAR(50)   NOT NULL,
    MESSAGE     VARCHAR(500)  NOT NULL,
    LOG_TS      TIMESTAMP_NTZ NOT NULL
)
CLUSTER BY (LOG_LEVEL, MODULE);

-- Insert data OUT of cluster order to trigger auto-reclustering
INSERT INTO DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG
SELECT
    SEQ4() + 1,
    CASE UNIFORM(1, 4, RANDOM())
        WHEN 1 THEN 'ERROR'
        WHEN 2 THEN 'WARN'
        WHEN 3 THEN 'INFO'
        ELSE 'DEBUG'
    END,
    CASE UNIFORM(1, 5, RANDOM())
        WHEN 1 THEN 'auth'
        WHEN 2 THEN 'api'
        WHEN 3 THEN 'scheduler'
        WHEN 4 THEN 'storage'
        ELSE 'network'
    END,
    'Log message number ' || SEQ4() || ' with random payload ' || REPEAT('x', UNIFORM(10, 100, RANDOM())),
    DATEADD(SECOND, -UNIFORM(0, 604800, RANDOM()), CURRENT_TIMESTAMP())
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

-- ============================================================================
-- 3. SERVERLESS_TASK — task using serverless compute (no warehouse)
--    Snowflake charges SERVERLESS_TASK credits for these.
-- ============================================================================
CREATE OR REPLACE TASK DSOA_TEST_DB.METERING_TEST.T_SERVERLESS_INSERT
    -- No WAREHOUSE clause = serverless task
    SCHEDULE = '5 MINUTE'
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AS
    INSERT INTO DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG (LOG_ID, LOG_LEVEL, MODULE, MESSAGE, LOG_TS)
    SELECT
        (SELECT COALESCE(MAX(LOG_ID), 0) FROM DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG) + SEQ4() + 1,
        CASE UNIFORM(1, 4, RANDOM())
            WHEN 1 THEN 'ERROR'
            WHEN 2 THEN 'WARN'
            WHEN 3 THEN 'INFO'
            ELSE 'DEBUG'
        END,
        'scheduler',
        'Serverless task insert at ' || CURRENT_TIMESTAMP()::VARCHAR,
        CURRENT_TIMESTAMP()
    FROM TABLE(GENERATOR(ROWCOUNT => 10));

ALTER TASK DSOA_TEST_DB.METERING_TEST.T_SERVERLESS_INSERT RESUME;

-- ============================================================================
-- 4. Additional inserts to keep auto-clustering active
--    Task inserts out-of-order data every 10 minutes.
-- ============================================================================
CREATE OR REPLACE TASK DSOA_TEST_DB.METERING_TEST.T_RECLUSTER_TRIGGER
    WAREHOUSE = DSOA_TEST_WH
    SCHEDULE  = '10 MINUTE'
AS
    INSERT INTO DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG (LOG_ID, LOG_LEVEL, MODULE, MESSAGE, LOG_TS)
    SELECT
        (SELECT COALESCE(MAX(LOG_ID), 0) FROM DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG) + SEQ4() + 1,
        -- Insert in REVERSE order of cluster key to force reclustering
        CASE MOD(SEQ4(), 4)
            WHEN 0 THEN 'DEBUG'
            WHEN 1 THEN 'INFO'
            WHEN 2 THEN 'WARN'
            ELSE 'ERROR'
        END,
        CASE MOD(SEQ4(), 5)
            WHEN 0 THEN 'network'
            WHEN 1 THEN 'storage'
            WHEN 2 THEN 'scheduler'
            WHEN 3 THEN 'api'
            ELSE 'auth'
        END,
        'Recluster trigger at ' || CURRENT_TIMESTAMP()::VARCHAR,
        CURRENT_TIMESTAMP()
    FROM TABLE(GENERATOR(ROWCOUNT => 100));

ALTER TASK DSOA_TEST_DB.METERING_TEST.T_RECLUSTER_TRIGGER RESUME;

-- ============================================================================
-- 5. Verify setup
-- ============================================================================
SHOW TASKS IN SCHEMA DSOA_TEST_DB.METERING_TEST;
SELECT SYSTEM$CLUSTERING_INFORMATION('DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG') AS clustering_info;
SELECT COUNT(*) AS row_count FROM DSOA_TEST_DB.METERING_TEST.CLUSTERED_LOG;

-- ============================================================================
-- 6. Config requirements
-- ============================================================================
-- In conf/config-test-qa.yml:
--   plugins:
--     metering:
--       is_enabled: true
--       lookback_hours: 6
--     event_usage:
--       is_enabled: false   # Deprecated by BDX-1865
--
-- Deploy:
--   ./scripts/deploy/deploy.sh test-qa --scope=plugins,config --options=skip_confirm

-- ============================================================================
-- 7. Verification DQL (run 1-3h after tasks start producing metering data)
-- ============================================================================
-- C2.11 — >=3 distinct service types:
--   timeseries sum(snowflake.credits.used), by:{snowflake.service.type}
--   | filter dsoa.run.plugin == "metering"
--   | filter deployment.environment == "DEV-095"
--
-- C3.7 — logs with service_type:
--   fetch logs
--   | filter dsoa.run.plugin == "metering"
--   | filter isNotNull(snowflake.service.type)
--   | summarize count(), by: {snowflake.service.type}
--
-- C8.4 — event_usage produces no data:
--   fetch logs
--   | filter dsoa.run.plugin == "event_usage"
--   | filter deployment.environment == "DEV-095"
--   | summarize count()
--   -- Expect: 0

-- ============================================================================
-- CLEANUP (run when done testing):
--   USE ROLE DTAGENT_QA_OWNER;
--   ALTER TASK DSOA_TEST_DB.METERING_TEST.T_SERVERLESS_INSERT SUSPEND;
--   ALTER TASK DSOA_TEST_DB.METERING_TEST.T_RECLUSTER_TRIGGER SUSPEND;
--   DROP SCHEMA IF EXISTS DSOA_TEST_DB.METERING_TEST CASCADE;
-- ============================================================================
